#DEV environment

app:
  message: This is the property file for the ${spring.application.name} specific to DEV environment
spring:
  data:
    mongodb:
      database: ${ENV_DB_NAME}
      uri: mongodb://localhost:27017
