#PROD environment

app:
  message: This is the property file for the ${spring.application.name} specific to PROD environment
server:
  port: 8080
spring:
  data:
    mongodb:
      database: ${ENV_DB_NAME}
      uri: mongodb+srv://${ENV_DB_USER}:${ENV_DB_PASS}@cluster0.jvxj2.mongodb.net/${ENV_DB_NAME}